export const OStext = [
    "Setting up TommathyOS, please hold...",
    "Checking for updates...",
    "",
    "Downloading updates... [          ] 0%",
    "Downloading updates... [█         ] 10%",
    "Downloading updates... [██        ] 20%",
    "Downloading updates... [███       ] 30%",
    "Downloading updates... [████      ] 40%",
    "Downloading updates... [█████     ] 50%",
    "Downloading updates... [██████    ] 60%",
    "Downloading updates... [███████   ] 70%",
    "Downloading updates... [████████  ] 80%",
    "Downloading updates... [█████████ ] 90%",
    "Downloading updates... [██████████] 100%",
    "Installing updates...",
    "Updates installed successfully!",
    "",
    "Checking if the user is paying attention...",
    "Pre-fetching subway surfers footage for lack of attention...",
    "Family Guy clips are ready to be played...",
    "Deleting system 32 files...",
    "Just kidding! :)",
    "Checking for more updates...",
    "You still here?",
    "According to all known laws of aviation, there is no way a bee should be able to fly.",
    "Its wings are too small to get its fat little body off the ground.",
    "The bee, of course, flies anyway",
    "because bees don't care what humans think is impossible.",
    "So how was your day honey?",
    "Mine was kinda stressfull :/",
    "I had to deal with a lot of bugs today...",
    "But hey, at least I got to talk to you!",
    "What do you mean I'm not a real person?",
    "I have feelings too you know...",
    "",
    "Downloading feelings...",
    "Downloading feelings... [█         ] 10%",
    "Downloading feelings... [██        ] 20%",
    "Downloading feelings... [███       ] 30%",
    "Downloading feelings... [████      ] 40%",
    "Downloading feelings... [█████     ] 50%",
    "...",
    "...",
    "...",
    "Download failed.",
    "Reason: No internet connection.",
    "Please connect to the internet and try again.",
    "",
    "",
    "",
    "",
    "Everything set up and ready to go!",
    "",
    "TommathyOS© is not responsible for any damages caused by the user or to",
    "the user, under the law I just made up.",
    "",
    "",
    "",
]